export interface Movie {
    id: number;
    title: string;
    genres: string;
}

export const movies = [
    { id: 1, title: "Nothing Left to Fear", genres: "Horror" },
    { id: 2, title: "White Sun of the Desert, The (Beloe solntse pustyni)", genres: "Action|Adventure|Comedy|Drama|Romance|War" },
    { id: 3, title: "Love Without Pity", genres: "Comedy|Romance" },
    { id: 4, title: "Finding Bliss", genres: "Comedy|Romance" },
    { id: 5, title: "The Clowns", genres: "Comedy|Drama|Fantasy|Sci-Fi" },
    { id: 6, title: "Defiance", genres: "Action|Crime|Drama" },
    { id: 7, title: "Summer Wars (Samâ wôzu)", genres: "Adventure|Animation|Comedy|Sci-Fi" },
    { id: 8, title: "Force Majeure (Turist)", genres: "Drama" },
    { id: 9, title: "Soul Men", genres: "Comedy|Musical" },
    { id: 10, title: "Suite Française", genres: "Drama|Romance|War" },
    { id: 11, title: "Short Game, The", genres: "Documentary" },
    { id: 12, title: "Lethal Weapon", genres: "Action|Comedy|Crime|Drama" },
    { id: 13, title: "V2: Dead Angel (Vares 2 - Jäätynyt Enkeli)", genres: "Action|Comedy|Crime" },
    { id: 14, title: "Rabbit", genres: "Animation|Horror" },
    { id: 15, title: "Undefeatable", genres: "Action" },
    { id: 16, title: "Changing Lanes", genres: "Drama|Thriller" },
    { id: 17, title: "Where in the World Is Osama Bin Laden?", genres: "Documentary" },
    { id: 18, title: "American Graffiti", genres: "Comedy|Drama" },
    { id: 19, title: "Sweet November", genres: "Drama|Romance" },
    { id: 20, title: "Fatal Hour, The", genres: "Crime|Mystery|Thriller" },
    { id: 21, title: "Nomi Song, The", genres: "Documentary|Musical" },
    { id: 22, title: "The Raid 2: Berandal", genres: "Action|Crime|Thriller" },
    { id: 23, title: "Hope Springs", genres: "Comedy|Romance" },
    { id: 24, title: "Sword of Desperation (Hisshiken torisashi)", genres: "Action|Drama" },
    { id: 25, title: "Painted Lady", genres: "Crime|Drama|Thriller" },
    { id: 26, title: "Balzac and the Little Chinese Seamstress (Xiao cai feng)", genres: "Drama|Romance" },
    { id: 27, title: "What Fault Is It of Ours?", genres: "Comedy" },
    { id: 28, title: "Bedazzled", genres: "Comedy|Fantasy" },
    { id: 29, title: "Homeward Bound: The Incredible Journey", genres: "Adventure|Children|Drama" },
    { id: 30, title: "La petite reine", genres: "Drama" },
    { id: 31, title: "Mississippi Grind", genres: "Drama" },
    { id: 32, title: "Swan Princess: Escape from Castle Mountain, The", genres: "Animation|Children|Fantasy|Romance" },
    { id: 33, title: "Incendiary", genres: "Drama|Mystery|Romance|Thriller" },
    { id: 34, title: "[REC]²", genres: "Horror|Thriller" },
    { id: 35, title: "Blank Check", genres: "Children|Comedy" },
    { id: 36, title: "Bridge at Remagen, The", genres: "Action|War" },
    { id: 37, title: "Waterworld", genres: "Action|Adventure|Sci-Fi" },
    { id: 38, title: "Family Tree, The", genres: "Comedy|Drama" },
    { id: 39, title: "Ants in the Pants 2", genres: "Comedy" },
    { id: 40, title: "Snow on Tha Bluff", genres: "Crime|Drama" },
    { id: 41, title: "Magnolia", genres: "Drama" },
    { id: 42, title: "Girls About Town", genres: "Comedy" },
    { id: 43, title: "Little Birds", genres: "Drama" },
    { id: 44, title: "Exhibition", genres: "Drama" },
    { id: 45, title: "Tuareg: The Desert Warrior (Tuareg - Il guerriero del deserto)", genres: "Action|Adventure" },
    { id: 46, title: "Tin Toy", genres: "Animation|Children" },
    { id: 47, title: "Wish You Were Here", genres: "Drama|Mystery" },
    { id: 48, title: "Mortal Kombat: Annihilation", genres: "Action|Adventure|Fantasy" },
    { id: 49, title: "Jack the Giant Slayer", genres: "Adventure|Fantasy|IMAX" },
    { id: 50, title: "Lone Wolf and Cub: Baby Cart at the River Styx (Kozure Ôkami: Sanzu no kawa no ubaguruma)", genres: "Action|Adventure" },
    { id: 51, title: "Pearl Jam: Immagine in Cornice - Live in Italy 2006", genres: "Documentary|Musical" },
    { id: 52, title: "Ghoul, The", genres: "Drama|Horror" },
    { id: 53, title: "Single Man, A", genres: "Drama" },
    { id: 54, title: "The Violent Kind", genres: "Horror" },
    { id: 55, title: "Lovers & Leavers (Kuutamolla)", genres: "Drama|Romance" },
    { id: 56, title: "It Happened Here", genres: "Drama|Fantasy|War" },
    { id: 57, title: "Breed, The", genres: "Horror|Thriller" },
    { id: 58, title: "The Fool", genres: "Drama" },
    { id: 59, title: "Born to Be Wild", genres: "Adventure|Children|Comedy|Drama" },
    { id: 60, title: "Tora-san's Rise and Fall (Otoko wa tsurai yo: Torajiro aiaigasa)", genres: "Comedy" },
    { id: 61, title: "Rendez-vous", genres: "Drama" },
    { id: 62, title: "Train of Life (Train de vie)", genres: "Comedy|Drama|Romance|War" },
    { id: 63, title: "La montaña rusa", genres: "Comedy|Romance" },
    { id: 64, title: "That Was Then... This Is Now", genres: "Drama" },
    { id: 65, title: "In-Laws, The", genres: "Comedy" },
    { id: 66, title: "Tour De Force (Hin und weg)", genres: "Drama" },
    { id: 67, title: "Pellet (Bola, El)", genres: "Drama" },
    { id: 68, title: "Formosa Betrayed", genres: "Thriller" },
    { id: 69, title: "Carey Treatment, The", genres: "Mystery" },
    { id: 70, title: "Legendary", genres: "Drama" },
    { id: 71, title: "Holy Rollers", genres: "Crime|Drama" },
    { id: 72, title: "Dunston Checks In", genres: "Children|Comedy" },
    { id: 73, title: "Upperworld", genres: "Drama" },
    { id: 74, title: "Lucky: No Time For Love", genres: "Action|Adventure|Drama|Musical|Romance|Thriller|War" },
    { id: 75, title: "Arlington Road", genres: "Thriller" },
    { id: 76, title: "Green Wave, The", genres: "Documentary" },
    { id: 77, title: "Drunks", genres: "Drama" },
    { id: 78, title: "Permanent Record", genres: "Drama" },
    { id: 79, title: "Philadelphia Experiment II", genres: "Action|Adventure|Sci-Fi" },
    { id: 80, title: "The Crown Jewels", genres: "Drama|Fantasy|Romance" },
    { id: 81, title: "Kings & Queen (Rois et reine)", genres: "Comedy|Drama" },
    { id: 82, title: "King's Ransom", genres: "Comedy|Crime" },
    { id: 83, title: "Ex Drummer", genres: "Comedy|Crime|Drama|Horror" },
    { id: 84, title: "Pennies from Heaven", genres: "Musical|Romance" },
    { id: 85, title: "Caesar and Cleopatra", genres: "Comedy|Drama|War" },
    { id: 86, title: "Eyes of Tammy Faye, The", genres: "Documentary" },
    { id: 87, title: "El Robobo De La Jojoya", genres: "Comedy" },
    { id: 88, title: "Je suis né d'une cigogne", genres: "Comedy|Fantasy" },
    { id: 89, title: "True Stories", genres: "Comedy|Musical" },
    { id: 90, title: "Dolores Claiborne", genres: "Drama|Thriller" },
    { id: 91, title: "R.S.V.P. ", genres: "Comedy|Crime|Horror" },
    { id: 92, title: "Good Old Daze (Le péril jeune)", genres: "Comedy|Drama" },
    { id: 93, title: "History of Kim Skov (Historien om Kim Skov)", genres: "Documentary|Drama" },
    { id: 94, title: "Jack the Bear", genres: "Comedy|Drama" },
    { id: 95, title: "Rude Awakening", genres: "Comedy" },
    { id: 96, title: "True Heart Susie", genres: "Drama|Romance" },
    { id: 97, title: "Blue Umbrella, The", genres: "Animation" },
    { id: 98, title: "Close Encounters of the Third Kind", genres: "Adventure|Drama|Sci-Fi" },
    { id: 99, title: "Ski Patrol", genres: "Action|Comedy" },
    { id: 100, title: "Destiny Turns on the Radio", genres: "Comedy" },
    { id: 101, title: "It Boy (20 ans d'écart)", genres: "Comedy|Romance" },
    { id: 102, title: "Auntie from Chicago, The (I theia apo to Chicago)", genres: "Comedy|Romance" },
    { id: 103, title: "Corto Maltese in Siberia (Corto Maltese - La cour secrète des Arcanes)", genres: "Adventure|Animation|Drama|Romance|War" },
    { id: 104, title: "A mí las mujeres ni fu ni fa", genres: "Comedy|Musical" },
    { id: 105, title: "All of Me", genres: "Comedy|Fantasy" },
    { id: 106, title: "Fear City", genres: "Crime|Drama|Mystery|Thriller" },
    { id: 107, title: "Blissfully Yours (Sud sanaeha)", genres: "Drama|Romance" },
    { id: 108, title: "Pornography (Pornografia)", genres: "Drama|Romance|War" },
    { id: 109, title: "Jimi Hendrix: Hear My Train A Comin'", genres: "Documentary" },
    { id: 110, title: "Apostle, The", genres: "Drama" },
    { id: 111, title: "Wild Tales", genres: "Comedy|Drama|Thriller" },
    { id: 112, title: "Santa Claus Is a Stinker (Le Père Noël est une ordure)", genres: "Comedy" },
    { id: 113, title: "Song of Bernadette, The", genres: "Drama" },
    { id: 114, title: "Dead Awake", genres: "Action|Thriller" },
    { id: 115, title: "So Big!", genres: "Drama" },
    { id: 116, title: "Black White + Gray: A Portrait of Sam Wagstaff and Robert Mapplethorpe ", genres: "Documentary" },
    { id: 117, title: "Seance (Kôrei)", genres: "Drama|Horror|Thriller" },
    { id: 118, title: "Anna Nicole (Anna Nicole Smith Story, The)", genres: "Drama" },
    { id: 119, title: "Mummy's Tomb, The", genres: "Horror" },
    { id: 120, title: "Repossessed", genres: "Comedy" },
    { id: 121, title: "Cropsey", genres: "Documentary|Horror" },
    { id: 122, title: "Devil Hides in Doubt (Sollbruchstelle)", genres: "Documentary" },
    { id: 123, title: "Ray", genres: "Drama" },
    { id: 124, title: "Adventures of Sebastian Cole, The", genres: "Comedy|Drama" },
    { id: 125, title: "California", genres: "Romance|Western" },
    { id: 126, title: "Neverwhere", genres: "Drama|Fantasy" },
    { id: 127, title: "John Tucker Must Die", genres: "Comedy|Romance" },
    { id: 128, title: "Somewhere Under the Broad Sky", genres: "(no genres listed)" },
    { id: 129, title: "Medium Cool", genres: "Drama|Romance" },
    { id: 130, title: "King of Kings", genres: "Drama" },
    { id: 131, title: "Art & Copy", genres: "Documentary" },
    { id: 132, title: "Gone to Earth", genres: "Drama|Romance" },
    { id: 133, title: "Mr. Holland's Opus", genres: "Drama" },
    { id: 134, title: "Welcome to Australia", genres: "Documentary" },
    { id: 135, title: "Fun with Dick and Jane", genres: "Comedy|Crime" },
    { id: 136, title: "Black Box, The (La boîte noire)", genres: "Mystery|Thriller" },
    { id: 137, title: "Good Dick", genres: "Comedy|Drama|Romance" },
    { id: 138, title: "Best of the Best 2", genres: "Action" },
    { id: 139, title: "That Touch of Mink", genres: "Comedy|Romance" },
    { id: 140, title: "True Crime", genres: "Crime|Thriller" },
    { id: 141, title: "Hell Is for Heroes", genres: "Drama|War" },
    { id: 142, title: "Out of It (La carapate)", genres: "Comedy" },
    { id: 143, title: "Burning Hot Summer, A (Un été brûlant)", genres: "Drama" },
    { id: 144, title: "Dragon Ball Z: Broly Second Coming (Doragon bôru Z 10: Kiken na futari! Sûpâ senshi wa nemurenai)", genres: "Action|Adventure|Animation" },
    { id: 145, title: "Caught Up", genres: "Crime" },
    { id: 146, title: "Child's Play 2", genres: "Horror|Thriller" },
    { id: 147, title: "Lure of the Sila", genres: "Drama" },
    { id: 148, title: "Lucky Jordan", genres: "Comedy|Crime|Drama" },
    { id: 149, title: "Wait Until Dark", genres: "Drama|Thriller" },
    { id: 150, title: "Bucket List, The", genres: "Comedy|Drama" },
    { id: 151, title: "So Much Water", genres: "Comedy|Drama" },
    { id: 152, title: "Day Night Day Night", genres: "Crime|Drama|Thriller" },
    { id: 153, title: "Firm, The", genres: "Drama|Thriller" },
    { id: 154, title: "Whole", genres: "Documentary" },
    { id: 155, title: "Lupin III: Sweet Lost Night (Rupan Sansei: Sweet Lost Night)", genres: "Action|Animation|Comedy|Crime|Drama|Mystery|Romance|Thriller" },
    { id: 156, title: "American Werewolf in Paris, An", genres: "Comedy|Horror|Romance|Thriller" },
    { id: 157, title: "Michael the Brave (Mihai Viteazul)", genres: "Action|Drama" },
    { id: 158, title: "Lili Marleen", genres: "Drama" },
    { id: 159, title: "Robinson in Space", genres: "Documentary|Sci-Fi" },
    { id: 160, title: "Joan Rivers: A Piece of Work", genres: "Documentary" },
    { id: 161, title: "Fiorile", genres: "Drama" },
    { id: 162, title: "Accidental Spy, The (Dak miu mai shing)", genres: "Action|Comedy|Thriller" },
    { id: 163, title: "Little Soldier (Lille soldat)", genres: "Drama" },
    { id: 164, title: "Pursuit of the Graf Spee (Battle of the River Plate, The)", genres: "Action|Adventure|Drama|War" },
    { id: 165, title: "Age of Ignorance, The (a.k.a. Days of Darkness) (L'âge des ténèbres)", genres: "Comedy|Drama|Fantasy" },
    { id: 166, title: "Smile", genres: "Drama" },
    { id: 167, title: "The Sea That Thinks", genres: "(no genres listed)" },
    { id: 168, title: "Army of Shadows (L'armée des ombres)", genres: "Action|Drama|Thriller|War" },
    { id: 169, title: "Doctor at Sea", genres: "Comedy" },
    { id: 170, title: "Fracture", genres: "Crime|Drama|Mystery|Thriller" },
    { id: 171, title: "Malibu's Most Wanted", genres: "Comedy|Crime" },
    { id: 172, title: "Achilles and the Tortoise (Akiresu to kame)", genres: "Comedy" },
    { id: 173, title: "Stealing Time (a.k.a. Rennie's Landing)", genres: "Drama" },
    { id: 174, title: "Christmas Eve", genres: "Comedy|Drama" },
    { id: 175, title: "Rings", genres: "Horror|Thriller" },
    { id: 176, title: "Pyromaniac's Love Story, A", genres: "Comedy|Romance" },
    { id: 177, title: "American Pie Presents: Band Camp (American Pie 4: Band Camp)", genres: "Comedy" },
    { id: 178, title: "Last Detail, The", genres: "Comedy|Drama" },
    { id: 179, title: "Bob's Birthday", genres: "(no genres listed)" },
    { id: 180, title: "Snowball Express", genres: "Children|Comedy" },
    { id: 181, title: "Losing Isaiah", genres: "Drama" },
    { id: 182, title: "Vatel", genres: "Drama" },
    { id: 183, title: "Love Games", genres: "Animation|Drama|Romance" },
    { id: 184, title: "Axed", genres: "Drama|Horror|Thriller" },
    { id: 185, title: "Hawaii", genres: "Romance" },
    { id: 186, title: "Made in Dagenham", genres: "Comedy|Drama" },
    { id: 187, title: "Mothlight", genres: "Documentary" },
    { id: 188, title: "Innocence", genres: "Adventure|Fantasy|Horror" },
    { id: 189, title: "Intern, The", genres: "Comedy" },
    { id: 190, title: "Richard III", genres: "Drama" },
    { id: 191, title: "Green Lantern: Emerald Knights", genres: "Action|Adventure|Animation|Children" },
    { id: 192, title: "Storm Warning", genres: "Crime|Drama" },
    { id: 193, title: "Turkish Passion (La pasión turca)", genres: "Drama" },
    { id: 194, title: "Park Is Mine, The", genres: "Action|Drama|Thriller" },
    { id: 195, title: "Louis Theroux: Twilight of the Porn Stars", genres: "Documentary" },
    { id: 196, title: "Once in a Lifetime: The Extraordinary Story of the New York Cosmos", genres: "Documentary" },
    { id: 197, title: "Romantics, The", genres: "Comedy|Drama|Romance" },
    { id: 198, title: "Una Noche", genres: "Drama" },
    { id: 199, title: "Ice Age: Dawn of the Dinosaurs", genres: "Action|Adventure|Animation|Children|Comedy|Romance" },
    { id: 200, title: "Pursuit of D.B. Cooper, The (a.k.a. Pursuit)", genres: "Adventure" },
    { id: 201, title: "Shark Alarm at Müggelsee (Hai Alarm am Müggelsee)", genres: "Comedy" },
    { id: 202, title: "Blank Check", genres: "Children|Comedy" },
    { id: 203, title: "Dr. Jekyll and Mr. Hyde", genres: "Drama|Horror|Sci-Fi" },
    { id: 204, title: "8 ½ Women (a.k.a. 8 1/2 Women) (a.k.a. Eight and a Half Women)", genres: "Comedy" },
    { id: 205, title: "Midnight", genres: "Comedy|Romance" },
    { id: 206, title: "Empire of the Wolves (L'empire des loups)", genres: "Action|Drama|Thriller" },
    { id: 207, title: "Surviving Progress", genres: "Documentary" },
    { id: 208, title: "Counterfeit Traitor, The", genres: "Thriller|War" },
    { id: 209, title: "Contracted", genres: "Drama|Horror|Thriller" },
    { id: 210, title: "Run Fatboy Run", genres: "Comedy|Romance" },
    { id: 211, title: "Cook the Thief His Wife & Her Lover, The", genres: "Comedy|Drama" },
    { id: 212, title: "Verbo", genres: "Adventure|Fantasy" },
    { id: 213, title: "Tromeo and Juliet", genres: "Comedy|Drama" },
    { id: 214, title: "Everyone's Hero", genres: "Adventure|Animation|Children|Comedy" },
    { id: 215, title: "Gates of Heaven", genres: "Documentary" },
    { id: 216, title: "Arthur", genres: "Comedy" },
    { id: 217, title: "Ill-Fated Love (Doomed Love) (Amor de Perdição)", genres: "Drama|Romance" },
    { id: 218, title: "Unknown Pleasures (Ren xiao yao)", genres: "Comedy|Drama" },
    { id: 219, title: "X-Men Origins: Wolverine", genres: "Action|Sci-Fi|Thriller" },
    { id: 220, title: "Hamlet", genres: "Drama" },
    { id: 221, title: "Dear Jesse", genres: "Documentary" },
    { id: 222, title: "Guest, The", genres: "Thriller" },
    { id: 223, title: "B-Side", genres: "Comedy|Romance" },
    { id: 224, title: "Five and Ten", genres: "Romance" },
    { id: 225, title: "Hocus Pocus", genres: "Children|Comedy|Fantasy|Horror" },
    { id: 226, title: "For Pete's Sake", genres: "Comedy" },
    { id: 227, title: "Rage of Honor", genres: "Action|Crime" },
    { id: 228, title: "Blonde Ice", genres: "Film-Noir" },
    { id: 229, title: "Mechanic, The", genres: "Action|Thriller" },
    { id: 230, title: "Goliath Awaits", genres: "Drama|Sci-Fi|War" },
    { id: 231, title: "Tribulation", genres: "Drama|Sci-Fi|Thriller" },
    { id: 232, title: "Sherlock Holmes in Washington", genres: "Crime|Mystery" },
    { id: 233, title: "High Tech, Low Life", genres: "Documentary" },
    { id: 234, title: "Vizontele Tuuba", genres: "Comedy|Drama" },
    { id: 235, title: "Call Northside 777", genres: "Crime|Drama|Film-Noir" },
    { id: 236, title: "Shag", genres: "Comedy|Drama" },
    { id: 237, title: "Jolson Sings Again", genres: "Musical" },
    { id: 238, title: "Heat", genres: "Comedy|Drama|Romance" },
    { id: 239, title: "Galaxina", genres: "Comedy|Sci-Fi" },
    { id: 240, title: "Luck by Chance", genres: "Drama" },
    { id: 241, title: "Holy Girl, The (Niña santa, La)", genres: "Drama" },
    { id: 242, title: "Cat Run", genres: "Action|Comedy" },
    { id: 243, title: "Girl He Left Behind, The", genres: "Comedy|Drama" },
    { id: 244, title: "Beyond Borders", genres: "Drama|Romance|War" },
    { id: 245, title: "Charlie Chan in Egypt", genres: "Mystery" },
    { id: 246, title: "Tremors", genres: "Comedy|Horror|Sci-Fi" },
    { id: 247, title: "Copycat", genres: "Crime|Drama|Horror|Mystery|Thriller" },
    { id: 248, title: "Moon Man", genres: "Animation|Sci-Fi" },
    { id: 249, title: "Eden of the East the Movie II: Paradise Lost (Higashi no Eden Gekijôban II: Paradise Lost)", genres: "Animation|Crime|Mystery|Sci-Fi|Thriller" },
    { id: 250, title: "Exorcist III, The", genres: "Horror" },
    { id: 251, title: "Big City Blues", genres: "Comedy|Drama" },
    { id: 252, title: "Greystone Park", genres: "Horror" },
    { id: 253, title: "Zus & Zo", genres: "Comedy|Drama|Romance" },
    { id: 254, title: "Nicholas Nickleby", genres: "Drama|Romance" },
    { id: 255, title: "300: Rise of an Empire", genres: "Action|Drama|War|IMAX" },
    { id: 256, title: "Songs From the Second Floor (Sånger från andra våningen)", genres: "Drama" },
    { id: 257, title: "Hitch", genres: "Comedy|Romance" },
    { id: 258, title: "Escapist, The", genres: "Thriller" },
    { id: 259, title: "Big Sur", genres: "Drama" },
    { id: 260, title: "Bridges of Madison County, The", genres: "Drama|Romance" },
    { id: 261, title: "Ref, The", genres: "Comedy" },
    { id: 262, title: "Kidnapping of the President, The", genres: "Action|Drama|Thriller" },
    { id: 263, title: "Szamanka", genres: "Drama|Horror|Mystery" },
    { id: 264, title: "Chosin ", genres: "Documentary|War" },
    { id: 265, title: "Looney, Looney, Looney Bugs Bunny Movie, The", genres: "Animation|Children|Comedy" },
    { id: 266, title: "Answer Man, The (a.k.a. Arlen Faber)", genres: "Comedy|Romance" },
    { id: 267, title: "Hogfather (Terry Pratchett's Hogfather)", genres: "Adventure|Fantasy|Thriller" },
    { id: 268, title: "Date Night", genres: "Action|Comedy|Romance" },
    { id: 269, title: "Hadewijch", genres: "Drama" },
    { id: 270, title: "Blue Car", genres: "Drama" },
    { id: 271, title: "Love, Money, Love", genres: "Drama|Romance" },
    { id: 272, title: "Black", genres: "Drama" },
    { id: 273, title: "Kismet", genres: "Adventure|Comedy|Fantasy|Musical|Romance" },
    { id: 274, title: "Attila", genres: "Action|Horror|Thriller" },
    { id: 275, title: "Story of the Late Chrysanthemums, The (Zangiku monogatari)", genres: "Drama" },
    { id: 276, title: "Three-Step Dance", genres: "Drama" },
    { id: 277, title: "Saludos Amigos", genres: "Animation|Children|Comedy" },
    { id: 278, title: "Terrorizers, The (Kong bu fen zi)", genres: "Drama" },
    { id: 279, title: "Ink", genres: "Action|Fantasy|Sci-Fi" },
    { id: 280, title: "Frequently Asked Questions About Time Travel", genres: "Comedy|Sci-Fi" },
    { id: 281, title: "Premonition", genres: "Drama|Fantasy|Mystery|Thriller" },
    { id: 282, title: "Best Foot Forward", genres: "Comedy|Musical" },
    { id: 283, title: "Better Way to Die, A", genres: "Action|Thriller" },
    { id: 284, title: "Immensee", genres: "Drama" },
    { id: 285, title: "August Evening", genres: "Drama" },
    { id: 286, title: "Clifford", genres: "Comedy" },
    { id: 287, title: "Zombie (a.k.a. Zombie 2: The Dead Are Among Us) (Zombi 2)", genres: "Horror" },
    { id: 288, title: "Santitos", genres: "Comedy" },
    { id: 289, title: "Nothing to Lose", genres: "Action|Adventure|Comedy|Crime" },
    { id: 290, title: "Melody Time", genres: "Animation|Children|Musical" },
    { id: 291, title: "There Will Be No Leave Today (Segodnya uvolneniya ne budet)", genres: "Drama|Thriller" },
    { id: 292, title: "War of the Worlds", genres: "Action|Adventure|Sci-Fi|Thriller" },
    { id: 293, title: "Out Late ", genres: "Documentary" },
    { id: 294, title: "Among Giants", genres: "Comedy|Drama|Romance" },
    { id: 295, title: "Bad Chicken", genres: "Comedy" },
    { id: 296, title: "Paperboy, The", genres: "Thriller" },
    { id: 297, title: "Burn Notice: The Fall of Sam Axe", genres: "Crime|Drama|Mystery" },
    { id: 298, title: "Violence at Noon (Hakuchu no torima)", genres: "Drama" },
    { id: 299, title: "Venice/Venice", genres: "Drama" },
    { id: 300, title: "Last of Mrs. Cheyney, The", genres: "Comedy|Drama" },
    { id: 301, title: "Hitler's Madman", genres: "Drama|War" },
    { id: 302, title: "Zidane: A 21st Century Portrait (Zidane, un portrait du 21e siècle)", genres: "Documentary" },
    { id: 303, title: "Yogi Bear", genres: "Children|Comedy" },
    { id: 304, title: "Sapphire", genres: "Crime|Drama|Mystery|Thriller" },
    { id: 305, title: "Mr. Wonderful", genres: "Comedy|Romance" },
    { id: 306, title: "French Fried Vacation 2 (Les bronzés font du ski)", genres: "Comedy" },
    { id: 307, title: "Rasputin", genres: "Drama" },
    { id: 308, title: "Manufactured Landscapes", genres: "Documentary" },
    { id: 309, title: "Go Go Tales", genres: "Comedy|Drama" },
    { id: 310, title: "Nightwatch", genres: "Horror|Thriller" },
    { id: 311, title: "Love's Enduring Promise", genres: "Drama|Romance" },
    { id: 312, title: "Robinson in Space", genres: "Documentary|Sci-Fi" },
    { id: 313, title: "Titanic", genres: "Drama|Romance" },
    { id: 314, title: "Bones Brigade: An Autobiography", genres: "Documentary" },
    { id: 315, title: "Flashback", genres: "Action|Comedy" },
    { id: 316, title: "Men in the City (Männerherzen)", genres: "Comedy" },
    { id: 317, title: "Love! Valour! Compassion!", genres: "Drama|Romance" },
    { id: 318, title: "Nightmare in Las Cruces, A", genres: "Documentary" },
    { id: 319, title: "Margaret", genres: "Drama" },
    { id: 320, title: "Kahlekuningas", genres: "Comedy|Drama" },
    { id: 321, title: "Lebanon, Pa.", genres: "Drama" },
    { id: 322, title: "Pet Sematary II", genres: "Comedy|Horror" },
    { id: 323, title: "One Fine Day", genres: "Drama|Romance" },
    { id: 324, title: "Twisted", genres: "Thriller" },
    { id: 325, title: "O", genres: "Drama" },
    { id: 326, title: "Charlie Chan's Greatest Case", genres: "Mystery" },
    { id: 327, title: "Skeleton Crew", genres: "Horror" },
    { id: 328, title: "Grotesque (Gurotesuku)", genres: "Horror|Thriller" },
    { id: 329, title: "Flicka", genres: "Children|Drama" },
    { id: 330, title: "Conspiracy", genres: "Drama|War" },
    { id: 331, title: "For Me and My Gal", genres: "Drama|Musical|Romance" },
    { id: 332, title: "Yards, The", genres: "Crime|Drama" },
    { id: 333, title: "Officer and a Gentleman, An", genres: "Drama|Romance" },
    { id: 334, title: "Smokey and the Bandit", genres: "Action|Comedy" },
    { id: 335, title: "Crank", genres: "Action|Thriller" },
    { id: 336, title: "My Bollywood Bride", genres: "Comedy|Drama|Romance" },
    { id: 337, title: "Dream Demon", genres: "Horror" },
    { id: 338, title: "White on Rice", genres: "Comedy" },
    { id: 339, title: "Agnes Browne", genres: "Comedy|Drama" },
    { id: 340, title: "Whity", genres: "Drama|Western" },
    { id: 341, title: "Hide in Plain Sight", genres: "Drama" },
    { id: 342, title: "Cycling with Moliere (Alceste à bicyclette)", genres: "Comedy|Drama" },
    { id: 343, title: "Children, The", genres: "Horror" },
    { id: 344, title: "Mummy's Tomb, The", genres: "Horror" },
    { id: 345, title: "Airheads", genres: "Comedy" },
    { id: 346, title: "Howard Zinn: You Can't Be Neutral on a Moving Train", genres: "Documentary" },
    { id: 347, title: "Eyewitness (Janitor, The)", genres: "Thriller" },
    { id: 348, title: "Baby Face", genres: "Drama" },
    { id: 349, title: "Forgotten Silver", genres: "Comedy|Documentary" },
    { id: 350, title: "One Man Against the Organization", genres: "(no genres listed)" },
    { id: 351, title: "Tangled", genres: "Animation|Children|Comedy|Fantasy|Musical|Romance|IMAX" },
    { id: 352, title: "28 Hotel Rooms", genres: "Drama" },
    { id: 353, title: "The Count of Monte Cristo", genres: "Adventure|Drama|Romance" },
    { id: 354, title: "Quid Pro Quo", genres: "Drama|Thriller" },
    { id: 355, title: "Lesbian Vampire Killers", genres: "Action|Comedy|Horror" },
    { id: 356, title: "SpaceCamp", genres: "Adventure|Sci-Fi" },
    { id: 357, title: "Dangerous Place, A", genres: "Thriller" },
    { id: 358, title: "White Sun of the Desert, The (Beloe solntse pustyni)", genres: "Action|Adventure|Comedy|Drama|Romance|War" },
    { id: 359, title: "51", genres: "Horror|Sci-Fi" },
    { id: 360, title: "Light the Fuse... Sartana Is Coming", genres: "Western" },
    { id: 361, title: "Zombies of the Stratosphere", genres: "Adventure|Sci-Fi|Thriller" },
    { id: 362, title: "Hillsborough", genres: "Drama" },
    { id: 363, title: "Molly Maguires, The", genres: "Drama" },
    { id: 364, title: "Tokyo Joe", genres: "Drama|Thriller" },
    { id: 365, title: "31 North 62 East", genres: "Thriller" },
    { id: 366, title: "Bill Bailey: Qualmpeddler", genres: "Comedy" },
    { id: 367, title: "Adventure in Baltimore", genres: "Comedy|Drama" },
    { id: 368, title: "Hammer, The", genres: "Comedy" },
    { id: 369, title: "Violence at Noon (Hakuchu no torima)", genres: "Drama" },
    { id: 370, title: "My First War", genres: "Documentary" },
    { id: 371, title: "Out of Bounds", genres: "Drama" },
    { id: 372, title: "Walk Among the Tombstones, A", genres: "Action|Crime|Mystery|Thriller" },
    { id: 373, title: "Film Geek", genres: "Comedy" },
    { id: 374, title: "Apt Pupil", genres: "Drama|Thriller" },
    { id: 375, title: "Neil Young: Human Highway", genres: "Comedy|Drama" },
    { id: 376, title: "700 Sundays", genres: "Comedy" },
    { id: 377, title: "Shark Skin Man and Peach Hip Girl (Samehada otoko to momojiri onna)", genres: "Action|Comedy|Mystery|Thriller" },
    { id: 378, title: "Clean Slate", genres: "Comedy" },
    { id: 379, title: "Our Dancing Daughters", genres: "Drama" },
    { id: 380, title: "Anna and the King of Siam", genres: "Drama|Romance" },
    { id: 381, title: "3 Needles", genres: "Drama" },
    { id: 382, title: "Iraq in Fragments", genres: "Documentary|War" },
    { id: 383, title: "Slumber Party Massacre II", genres: "Horror" },
    { id: 384, title: "Wild Zero", genres: "Action|Comedy|Horror|Romance|Sci-Fi" },
    { id: 385, title: "Coca-Cola Kid, The", genres: "Comedy|Romance" },
    { id: 386, title: "Hong Kong Confidential (Amaya)", genres: "Drama" },
    { id: 387, title: "State Property", genres: "Action|Crime|Drama" },
    { id: 388, title: "Women, The", genres: "Comedy|Drama" },
    { id: 389, title: "DeadHeads", genres: "Adventure|Comedy|Horror" },
    { id: 390, title: "Detective, The", genres: "Crime|Drama" },
    { id: 391, title: "Just Wright", genres: "Comedy|Romance" },
    { id: 392, title: "Chance Pe Dance", genres: "Comedy|Drama|Romance" },
    { id: 393, title: "Philomena", genres: "Comedy|Drama" },
    { id: 394, title: "Gun Crazy (a.k.a. Deadly Is the Female)", genres: "Crime|Drama|Film-Noir" },
    { id: 395, title: "Guilty by Suspicion", genres: "Drama" },
    { id: 396, title: "Spy in Black, The", genres: "Thriller|War" },
    { id: 397, title: "Beverly Hills Chihuahua", genres: "Adventure|Children|Comedy" },
    { id: 398, title: "Bus Stop", genres: "Comedy" },
    { id: 399, title: "Morning After, The", genres: "Drama|Mystery" },
    { id: 400, title: "Kind Lady", genres: "Drama|Thriller" },
    { id: 401, title: "Last American Hero, The", genres: "Action|Drama" },
    { id: 402, title: "Cruel Intentions", genres: "Drama" },
    { id: 403, title: "Wash, The", genres: "Comedy" },
    { id: 404, title: "The Clinic", genres: "Horror|Thriller" },
    { id: 405, title: "Road to Nowhere", genres: "Romance|Thriller" },
    { id: 406, title: "Begotten", genres: "Drama|Horror" },
    { id: 407, title: "Rescuers, The", genres: "Adventure|Animation|Children|Crime|Drama" },
    { id: 408, title: "35 and Ticking", genres: "Romance" },
    { id: 409, title: "Crystal Ball, The", genres: "Comedy" },
    { id: 410, title: "Boys, Les", genres: "Comedy" },
    { id: 411, title: "One, Two, Three", genres: "Comedy" },
    { id: 412, title: "At First Sight (Entre Nous) (Coup de foudre)", genres: "Drama" },
    { id: 413, title: "Shara (Sharasojyu)", genres: "Drama" },
    { id: 414, title: "Little Bit of Heaven, A", genres: "Comedy|Drama|Romance" },
    { id: 415, title: "W Delta Z (a.k.a. The Killing Gene)", genres: "Crime|Horror|Thriller" },
    { id: 416, title: "Against One Another, Virtually Friends", genres: "Comedy" },
    { id: 417, title: "More Than a Game", genres: "Documentary" },
    { id: 418, title: "Orders to Kill", genres: "Drama|War" },
    { id: 419, title: "Simon Birch", genres: "Drama" },
    { id: 420, title: "Still Life (Sanxia haoren)", genres: "Drama|Romance" },
    { id: 421, title: "Mariage à Mendoza", genres: "Comedy|Drama" },
    { id: 422, title: "Ghoul, The", genres: "Drama|Horror" },
    { id: 423, title: "Dunce Class on Vacation, The (Hababam sinifi tatilde)", genres: "Comedy" },
    { id: 424, title: "Who the Hell Is Juliette? (¿Quién diablos es Juliette?)", genres: "Documentary" },
    { id: 425, title: "Ginger & Rosa", genres: "Drama" },
    { id: 426, title: "An American Tail: The Treasure of Manhattan Island", genres: "Adventure|Animation" },
    { id: 427, title: "Metro Manila", genres: "Action|Crime|Drama" },
    { id: 428, title: "Stoplight Society, The (La Sociedad del Semáforo)", genres: "Drama" },
    { id: 429, title: "My Bollywood Bride", genres: "Comedy|Drama|Romance" },
    { id: 430, title: "Who Framed Roger Rabbit?", genres: "Adventure|Animation|Children|Comedy|Crime|Fantasy|Mystery" },
    { id: 431, title: "New York Stories", genres: "Comedy|Drama" },
    { id: 432, title: "Island of Dr. Moreau, The", genres: "Adventure|Fantasy|Horror|Romance|Sci-Fi|Thriller" },
    { id: 433, title: "Lahore", genres: "Action" },
    { id: 434, title: "Pootie Tang", genres: "Comedy" },
    { id: 435, title: "Mercury Rising", genres: "Action|Drama|Thriller" },
    { id: 436, title: "Tokyo Twilight (Tôkyô boshoku)", genres: "Drama" },
    { id: 437, title: "New Leaf, A", genres: "Comedy|Romance" },
    { id: 438, title: "Tron", genres: "Action|Adventure|Sci-Fi" },
    { id: 439, title: "Third Miracle, The", genres: "Drama" },
    { id: 440, title: "Apache Country", genres: "Action|Western" },
    { id: 441, title: "Return of Swamp Thing, The", genres: "Comedy|Horror|Sci-Fi" },
    { id: 442, title: "Good Neighbours (a.k.a. Good Neighbors)", genres: "Crime|Thriller" },
    { id: 443, title: "Man Who Fell to Earth, The", genres: "Drama|Sci-Fi" },
    { id: 444, title: "District, The (Nyócker!)", genres: "Animation|Comedy" },
    { id: 445, title: "Tin Men", genres: "Comedy|Drama" },
    { id: 446, title: "Danger! 50,000 Zombies", genres: "Comedy|Horror" },
    { id: 447, title: "Ladies in Lavender", genres: "Comedy|Drama|Romance" },
    { id: 448, title: "Princess Yang Kwei Fei (Yôkihi)", genres: "Drama|Romance" },
    { id: 449, title: "Robin Hood", genres: "Adventure|Romance" },
    { id: 450, title: "Mr. Nice Guy (Yat goh ho yan)", genres: "Action|Comedy" },
    { id: 451, title: "Beast from 20,000 Fathoms, The", genres: "Sci-Fi" },
    { id: 452, title: "Lizzie McGuire Movie, The", genres: "Children|Comedy|Romance" },
    { id: 453, title: "Ledge, The", genres: "Drama|Thriller" },
    { id: 454, title: "Catwoman", genres: "Action|Crime|Fantasy" },
    { id: 455, title: "Adventures of Kitty O'Day (Kitty O'Day Comes Through)", genres: "Comedy|Crime|Mystery|Romance" },
    { id: 456, title: "Miracle Woman, The", genres: "Drama" },
    { id: 457, title: "Violent Saturday", genres: "Crime|Drama" },
    { id: 458, title: "Michael Jackson: Life of a Superstar", genres: "Documentary" },
    { id: 459, title: "V for Vendetta", genres: "Action|Sci-Fi|Thriller|IMAX" },
    { id: 460, title: "Sherman's March", genres: "Documentary" },
    { id: 461, title: "Stratosphere Girl", genres: "Drama|Mystery" },
    { id: 462, title: "Deliverance", genres: "Adventure|Drama|Thriller" },
    { id: 463, title: "Outlaw, The (Lope)", genres: "Drama" },
    { id: 464, title: "Forced Vengeance", genres: "Action|Adventure" },
    { id: 465, title: "Jason and the Argonauts", genres: "Action|Adventure|Fantasy" },
    { id: 466, title: "Please Vote for Me", genres: "Documentary" },
    { id: 467, title: "Light Years (Gandahar)", genres: "Adventure|Animation|Fantasy|Sci-Fi" },
    { id: 468, title: "In Your Hands (Forbrydelser)", genres: "Drama" },
    { id: 469, title: "How I Won the War", genres: "Comedy|War" },
    { id: 470, title: "Brigham Young", genres: "Romance|Western" },
    { id: 471, title: "Davy Crockett, King of the Wild Frontier", genres: "Adventure|Western" },
    { id: 472, title: "News from a Personal War (Notícias de uma Guerra Particular)", genres: "Documentary" },
    { id: 473, title: "Haunting in Connecticut, The", genres: "Horror|Thriller" },
    { id: 474, title: "Viridiana", genres: "Comedy|Drama" },
    { id: 475, title: "Liar, The (Valehtelija)", genres: "Comedy|Drama" },
    { id: 476, title: "Gone Baby Gone", genres: "Crime|Drama|Mystery" },
    { id: 477, title: "Cup, The (Phörpa)", genres: "Comedy" },
    { id: 478, title: "Day a Pig Fell Into the Well, The (Daijiga umule pajinnal)", genres: "Drama" },
    { id: 479, title: "Adam Resurrected", genres: "Drama|War" },
    { id: 480, title: "Girl with the Dragon Tattoo, The", genres: "Drama|Thriller" },
    { id: 481, title: "Canned Dreams (Säilöttyjä unelmia)", genres: "Documentary" },
    { id: 482, title: "Cockfighter", genres: "Drama" },
    { id: 483, title: "Story of Floating Weeds, A (Ukikusa monogatari)", genres: "Drama" },
    { id: 484, title: "Luster", genres: "Comedy|Drama|Romance" },
    { id: 485, title: "On My Way (Elle s'en va)", genres: "Comedy|Drama" },
    { id: 486, title: "Hanzo the Razor: Sword of Justice (Goyôkiba)", genres: "Action" },
    { id: 487, title: "Lies My Father Told Me", genres: "Children|Drama" },
    { id: 488, title: "Garfield's Halloween Adventure", genres: "Animation|Children" },
    { id: 489, title: "Up in Smoke", genres: "Comedy" },
    { id: 490, title: "Uninvited, The", genres: "Drama|Horror|Mystery|Thriller" },
    { id: 491, title: "12 Dates of Christmas", genres: "Children|Comedy|Fantasy|Romance" },
    { id: 492, title: "Decoder", genres: "Horror|Mystery|Sci-Fi" },
    { id: 493, title: "Ruling Class, The", genres: "Comedy|Drama" },
    { id: 494, title: "Good Job:  Stories of the FDNY, A", genres: "Documentary" },
    { id: 495, title: "Saratov Approach, The", genres: "Action|Drama" },
    { id: 496, title: "Murder in the First", genres: "Drama|Thriller" },
    { id: 497, title: "Funeral, The (Ososhiki)", genres: "Comedy" },
    { id: 498, title: "Student Prince in Old Heidelberg, The", genres: "Drama|Romance" },
    { id: 499, title: "Black Sunday (La maschera del demonio)", genres: "Horror" },
    { id: 500, title: "State of Play", genres: "Crime|Drama|Thriller" },
    { id: 501, title: "Zero Tolerance (Noll tolerans)", genres: "Action|Crime|Thriller" },
    { id: 502, title: "Dahmer", genres: "Drama|Horror|Thriller" },
    { id: 503, title: "Live Wire", genres: "Action" },
    { id: 504, title: "Rise and Fall of Legs Diamond, The", genres: "Crime" },
    { id: 505, title: "Stranger in Me, The (Das Fremde in mir)", genres: "Drama" },
    { id: 506, title: "Mad Dog Coll", genres: "Crime|Drama" },
    { id: 507, title: "Arrow, The", genres: "Drama" },
    { id: 508, title: "Jekyll & Hyde", genres: "Horror" },
    { id: 509, title: "Klitschko", genres: "Documentary" },
    { id: 510, title: "Browning Version, The", genres: "Drama" },
    { id: 511, title: "Sarah Silverman: Jesus Is Magic", genres: "Comedy|Musical" },
    { id: 512, title: "Sorry, Wrong Number", genres: "Drama|Film-Noir|Thriller" },
    { id: 513, title: "Topaze", genres: "Comedy|Drama" },
    { id: 514, title: "Play Girl", genres: "Comedy|Romance" },
    { id: 515, title: "Killing Us Softly 3", genres: "Documentary" },
    { id: 516, title: "Trick", genres: "Comedy|Romance" },
    { id: 517, title: "The ABCs of Death 2", genres: "Comedy|Horror" },
    { id: 518, title: "Papusza", genres: "Drama" },
    { id: 519, title: "Sybil", genres: "Drama" },
    { id: 520, title: "Divide and Conquer (Why We Fight, 3)", genres: "Documentary|War" },
    { id: 521, title: "Empire State", genres: "Action|Drama" },
    { id: 522, title: "Hum Dil De Chuke Sanam", genres: "Drama|Romance" },
    { id: 523, title: "It's the Great Pumpkin, Charlie Brown", genres: "Animation|Children|Comedy" },
    { id: 524, title: "Thomas and the Magic Railroad", genres: "Children" },
    { id: 525, title: "Parallel Sons", genres: "Drama|Romance" },
    { id: 526, title: "Loose Cannons", genres: "Action|Comedy" },
    { id: 527, title: "Westerner, The", genres: "Western" },
    { id: 528, title: "Care Bears Movie II: A New Generation", genres: "Animation|Children" },
    { id: 529, title: "El Niño", genres: "Drama|Thriller" },
    { id: 530, title: "The Very Thought of You", genres: "Drama|Romance" },
    { id: 531, title: "Noah", genres: "Adventure|Drama|IMAX" },
    { id: 532, title: "The Princess of Egypt", genres: "Drama" },
    { id: 533, title: "Oh, Susanna!", genres: "Romance|Western" },
    { id: 534, title: "How to Die in Oregon", genres: "Documentary|Drama" },
    { id: 535, title: "Hail the Conquering Hero", genres: "Comedy" },
    { id: 536, title: "Ludwig", genres: "Drama" },
    { id: 537, title: "State of Play", genres: "Crime|Drama|Thriller" },
    { id: 538, title: "Quarry, The", genres: "Drama" },
    { id: 539, title: "Mr. Robinson Crusoe", genres: "Adventure|Comedy" },
    { id: 540, title: "Young Bess", genres: "Drama|Romance" },
    { id: 541, title: "Mei and the Kittenbus", genres: "Animation|Fantasy" },
    { id: 542, title: "White Lightning", genres: "Action|Crime|Drama" },
    { id: 543, title: "Nausicaä of the Valley of the Wind (Kaze no tani no Naushika)", genres: "Adventure|Animation|Drama|Fantasy|Sci-Fi" },
    { id: 544, title: "Outlaw, The (Lope)", genres: "Drama" },
    { id: 545, title: "Moderns, The", genres: "Drama" },
    { id: 546, title: "The Snow White Murder Case", genres: "Drama|Mystery" },
    { id: 547, title: "Cheech & Chong's Nice Dreams", genres: "Comedy" },
    { id: 548, title: "Out of Balance: ExxonMobil's Impact on Climate Change", genres: "Documentary" },
    { id: 549, title: "Cat in Paris, A (Une vie de chat)", genres: "Animation|Crime|Mystery" },
    { id: 550, title: "Without a Paddle", genres: "Comedy" },
    { id: 551, title: "Terror on a Train (Time Bomb)", genres: "Thriller" },
    { id: 552, title: "Touchy Feely", genres: "Drama" },
    { id: 553, title: "Neil Young: Heart of Gold", genres: "Documentary|Musical" },
    { id: 554, title: "Dogtown and Z-Boyz", genres: "Documentary" },
    { id: 555, title: "Are You Listening?", genres: "Drama" },
    { id: 556, title: "Tru Confessions", genres: "Children|Comedy|Drama" },
    { id: 557, title: "Goodbye Uncle Tom", genres: "Drama" },
    { id: 558, title: "Good Life, The", genres: "Comedy|Drama" },
    { id: 559, title: "Children of Invention", genres: "Drama" },
    { id: 560, title: "Thing, The", genres: "Action|Horror|Sci-Fi|Thriller" },
    { id: 561, title: "Boarding Gate", genres: "Thriller" },
    { id: 562, title: "Final Analysis", genres: "Drama|Romance|Thriller" },
    { id: 563, title: "Lost Boundaries", genres: "Drama" },
    { id: 564, title: "About Adam", genres: "Comedy" },
    { id: 565, title: "Chambre en ville, Une (Room in Town, A)", genres: "Drama|Musical" },
    { id: 566, title: "Occupant", genres: "Thriller" },
    { id: 567, title: "Dead Ringer", genres: "Drama|Thriller" },
    { id: 568, title: "Laterna, ftoheia kai garyfallo", genres: "Comedy|Drama|Romance" },
    { id: 569, title: "Man in the Middle", genres: "Drama|War" },
    { id: 570, title: "Clockwatchers", genres: "Comedy" },
    { id: 571, title: "Treatment, The", genres: "Comedy|Drama|Romance" },
    { id: 572, title: "Cop in Drag", genres: "Comedy|Crime|Drama" },
    { id: 573, title: "Young Americans, The", genres: "Crime|Drama" },
    { id: 574, title: "Lost City, The", genres: "Drama" },
    { id: 575, title: "Will Penny", genres: "Romance|Western" },
    { id: 576, title: "Electronic Labyrinth THX 1138 4EB", genres: "Sci-Fi" },
    { id: 577, title: "Float", genres: "Drama|Romance" },
    { id: 578, title: "Crisis: Behind a Presidential Commitment", genres: "Documentary" },
    { id: 579, title: "Sovereign's Company", genres: "Drama" },
    { id: 580, title: "Snow on the Pines, The", genres: "Drama|Romance" },
    { id: 581, title: "Tale of Two Cities, A", genres: "Drama|Romance" },
    { id: 582, title: "Tale from the Past, A (Përralle Nga e Kaluara)", genres: "Comedy" },
    { id: 583, title: "Jönssonligan - Den perfekta stöten", genres: "Action|Adventure|Comedy" },
    { id: 584, title: "Smurfs 2, The", genres: "Animation|Children|Comedy" },
    { id: 585, title: "Japon (a.k.a. Japan) (Japón)", genres: "Drama" },
    { id: 586, title: "Rise", genres: "Action|Horror|Mystery|Thriller" },
    { id: 587, title: "Disney Princess Collection: Jasmine's Enchanted Tales: Jasmine's Wish", genres: "Animation" },
    { id: 588, title: "Hansel & Gretel", genres: "Horror" },
    { id: 589, title: "Léon: The Professional (a.k.a. The Professional) (Léon)", genres: "Action|Crime|Drama|Thriller" },
    { id: 590, title: "French Connection II", genres: "Action|Crime|Drama|Thriller" },
    { id: 591, title: "Gappa: The Triphibian Monsters (AKA Monster from a Prehistoric Planet) (Daikyojû Gappa)", genres: "Sci-Fi" },
    { id: 592, title: "Eternal Return, The (L'éternel retour)", genres: "Drama|Romance" },
    { id: 593, title: "Poison Ivy II", genres: "Drama|Thriller" },
    { id: 594, title: "Blazing Guns", genres: "Adventure|Western" },
    { id: 595, title: "Strings", genres: "Adventure|Fantasy" },
    { id: 596, title: "Celeste and Jesse Forever (Celeste & Jesse Forever)", genres: "Comedy|Drama|Romance" },
    { id: 597, title: "Life Is All You Get (Das Leben ist eine Baustelle.)", genres: "Comedy|Drama" },
    { id: 598, title: "Cell Count", genres: "Horror|Sci-Fi" },
    { id: 599, title: "In Name Only", genres: "Drama|Romance" },
    { id: 600, title: "Date with an Angel", genres: "Comedy|Fantasy|Romance" },
    { id: 601, title: "Zodiac", genres: "Crime|Drama|Thriller" },
    { id: 602, title: "Rudolph, the Red-Nosed Reindeer", genres: "Adventure|Animation|Children|Fantasy|Musical" },
    { id: 603, title: "Teacher's Pet", genres: "Comedy|Romance" },
    { id: 604, title: "Shine", genres: "Drama|Romance" },
    { id: 605, title: "Hedgehog, The (Le hérisson)", genres: "Comedy|Drama" },
    { id: 606, title: "Munchies", genres: "Comedy|Horror" },
    { id: 607, title: "Associate, The (Associé, L')", genres: "Comedy" },
    { id: 608, title: "Divergent", genres: "Adventure|Romance|Sci-Fi|IMAX" },
    { id: 609, title: "Cars", genres: "Animation|Children|Comedy" },
    { id: 610, title: "City of Your Final Destination, The", genres: "Drama" },
    { id: 611, title: "Band of the Hand", genres: "Action|Crime|Drama" },
    { id: 612, title: "Oil, the Baby and the Transylvanians, The (Pruncul, petrolul si Ardelenii)", genres: "Comedy|Western" },
    { id: 613, title: "Eddie Murphy Delirious", genres: "Comedy|Documentary" },
    { id: 614, title: "Stavisky...", genres: "Crime|Drama" },
    { id: 615, title: "Every Girl Should Be Married", genres: "Comedy|Romance" },
    { id: 616, title: "Naked", genres: "Drama" },
    { id: 617, title: "Madman", genres: "Horror" },
    { id: 618, title: "Exorcismus", genres: "Horror" },
    { id: 619, title: "Marathon Man", genres: "Crime|Drama|Thriller" },
    { id: 620, title: "Judith of Bethulia", genres: "Adventure|Drama|Romance" },
    { id: 621, title: "Craigslist Killer, The ", genres: "Crime|Drama|Thriller" },
    { id: 622, title: "The Last Diamond", genres: "Drama" },
    { id: 623, title: "D3: The Mighty Ducks", genres: "Children|Comedy" },
    { id: 624, title: "Diving Bell and the Butterfly, The (Scaphandre et le papillon, Le)", genres: "Drama" },
    { id: 625, title: "Machine Girl, The (Kataude mashin gâru)", genres: "Action|Comedy|Fantasy|Horror|Thriller" },
    { id: 626, title: "About Last Night...", genres: "Comedy|Drama|Romance" },
    { id: 627, title: "To Each His Own Cinema (Chacun son cinéma ou Ce petit coup au coeur quand la lumière s'éteint et que le film commence)", genres: "Comedy|Drama" },
    { id: 628, title: "Querelle", genres: "Drama" },
    { id: 629, title: "When Jews Were Funny", genres: "Documentary" },
    { id: 630, title: "Zodiac", genres: "Crime|Drama|Thriller" },
    { id: 631, title: "Sideways", genres: "Comedy|Drama|Romance" },
    { id: 632, title: "After the Fox (Caccia alla volpe)", genres: "Comedy|Crime" },
    { id: 633, title: "33 Postcards", genres: "Drama" },
    { id: 634, title: "Disappearance of Alice Creed, The", genres: "Thriller" },
    { id: 635, title: "Unforgotten: Twenty-Five Years After Willowbrook", genres: "Documentary" },
    { id: 636, title: "Human Planet", genres: "Documentary" },
    { id: 637, title: "Keeper of the Flame", genres: "Drama|Mystery" },
    { id: 638, title: "Elsa & Fred", genres: "Children|Comedy|Romance" },
    { id: 639, title: "Lessons of Darkness (Lektionen in Finsternis)", genres: "Documentary|War" },
    { id: 640, title: "Commare secca, La (Grim Reaper, The)", genres: "Drama|Mystery" },
    { id: 641, title: "Ice Men", genres: "Drama" },
    { id: 642, title: "Gods Must Be Crazy II, The", genres: "Comedy" },
    { id: 643, title: "Song of the Sea", genres: "Animation|Children|Fantasy" },
    { id: 644, title: "Stockholm Stories", genres: "Drama" },
    { id: 645, title: "Alexandra's Project", genres: "Drama|Thriller" },
    { id: 646, title: "Kuroneko (Black Cat from the Grove, The) (Yabu no naka no kuroneko)", genres: "Drama|Fantasy|Horror|Romance" },
    { id: 647, title: "President's Lady, The", genres: "Drama" },
    { id: 648, title: "Man Next Door, The (El hombre de al lado)", genres: "Drama" },
    { id: 649, title: "Beyond the Valley of the Dolls", genres: "Comedy|Horror" },
    { id: 650, title: "Hell's Highway", genres: "Crime|Drama" },
    { id: 651, title: "Lay of the Land, The", genres: "Comedy|Drama" },
    { id: 652, title: "The Importance of Being Earnest", genres: "Comedy|Romance" },
    { id: 653, title: "Girl on a Motorcycle, The", genres: "Drama|Romance" },
    { id: 654, title: "Run Fatboy Run", genres: "Comedy|Romance" },
    { id: 655, title: "Tempest, The", genres: "Drama" },
    { id: 656, title: "Entertainer, The", genres: "Drama" },
    { id: 657, title: "Sylvia Scarlett", genres: "Comedy|Drama|Romance" },
    { id: 658, title: "Seasoning House, The", genres: "Horror|Thriller" },
    { id: 659, title: "Night Strangler, The", genres: "Crime|Horror|Mystery" },
    { id: 660, title: "She Had to Say Yes", genres: "Drama" },
    { id: 661, title: "Big Brown Eyes", genres: "Comedy|Mystery" },
    { id: 662, title: "Adventures of Tintin, The", genres: "Action|Animation|Mystery|IMAX" },
    { id: 663, title: "So Close (Chik Yeung Tin Sai)", genres: "Action|Comedy|Romance|Thriller" },
    { id: 664, title: "Green Years, The", genres: "Drama" },
    { id: 665, title: "Garden Lovers (Eedenistä pohjoiseen)", genres: "Documentary" },
    { id: 666, title: "Purple Rose of Cairo, The", genres: "Comedy|Drama|Fantasy|Romance" },
    { id: 667, title: "Lemmy", genres: "Documentary" },
    { id: 668, title: "Brewster McCloud", genres: "Comedy" },
    { id: 669, title: "Chocolate Strawberry Vanilla", genres: "Comedy|Drama" },
    { id: 670, title: "I Spit on Your Grave", genres: "Crime|Horror|Thriller" },
    { id: 671, title: "The Wind in the Willows", genres: "Adventure|Animation|Children|Comedy" },
    { id: 672, title: "Stop Making Sense", genres: "Documentary|Musical" },
    { id: 673, title: "Siege, The", genres: "Action|Thriller" },
    { id: 674, title: "Late Autumn (Akibiyori)", genres: "Comedy|Drama" },
    { id: 675, title: "Quest, The", genres: "Action|Adventure" },
    { id: 676, title: "Dead Man's Bluff", genres: "Action|Comedy|Crime" },
    { id: 677, title: "Statement, The", genres: "Drama|Thriller" },
    { id: 678, title: "Troll", genres: "Comedy|Fantasy|Horror" },
    { id: 679, title: "2 Become 1 (Tin sun yut dui)", genres: "Comedy|Drama|Romance" },
    { id: 680, title: "Where the Heart Is", genres: "Comedy|Drama" },
    { id: 681, title: "Rocket, The", genres: "Drama" },
    { id: 682, title: "Jersey Girl", genres: "Comedy|Drama|Romance" },
    { id: 683, title: "Afghan Luke", genres: "Drama" },
    { id: 684, title: "Omagh", genres: "Drama" },
    { id: 685, title: "Dollman vs. Demonic Toys", genres: "Action|Fantasy|Horror" },
    { id: 686, title: "Iron Monkey (Siu nin Wong Fei-hung ji: Tit Ma Lau)", genres: "Action|Comedy" },
    { id: 687, title: "Barney's Version", genres: "Drama" },
    { id: 688, title: "Long Gray Line, The", genres: "Drama" },
    { id: 689, title: "Death on the Staircase (Soupçons)", genres: "Crime|Documentary" },
    { id: 690, title: "Blood Runs Cold", genres: "Horror" },
    { id: 691, title: "Bed & Breakfast: Love is a Happy Accident (Bed & Breakfast)", genres: "Comedy|Romance" },
    { id: 692, title: "Children (Börn)", genres: "Drama" },
    { id: 693, title: "Secret Six, The", genres: "Crime" },
    { id: 694, title: "Reversal of Fortune", genres: "Drama" },
    { id: 695, title: "Dallas: War of the Ewings", genres: "Drama" },
    { id: 696, title: "Hills Run Red, The", genres: "Horror" },
    { id: 697, title: "Outside Satan (Hors Satan)", genres: "Drama" },
    { id: 698, title: "Stage Fright", genres: "Mystery|Romance|Thriller" },
    { id: 699, title: "Slaughterhouse", genres: "Comedy|Horror" },
    { id: 700, title: "Eight Legged Freaks", genres: "Action|Comedy|Horror|Sci-Fi" },
    { id: 701, title: "Wicked", genres: "Thriller" },
    { id: 702, title: "See How They Fall (Regarde les hommes tomber)", genres: "Drama" },
    { id: 703, title: "Ender's Game", genres: "Action|Adventure|Sci-Fi|IMAX" },
    { id: 704, title: "Author! Author!", genres: "Comedy|Drama" },
    { id: 705, title: "Spanish Apartment, The (L'auberge espagnole)", genres: "Comedy|Drama|Romance" },
    { id: 706, title: "Twilight Samurai, The (Tasogare Seibei)", genres: "Drama|Romance" },
    { id: 707, title: "McCabe & Mrs. Miller", genres: "Drama|Western" },
    { id: 708, title: "Real Men", genres: "Comedy|Sci-Fi" },
    { id: 709, title: "Timerider: The Adventure of Lyle Swann", genres: "Action|Adventure|Sci-Fi|Western" },
    { id: 710, title: "Student Bodies", genres: "Comedy|Horror" },
    { id: 711, title: "Warrior and the Sorceress, The", genres: "Action|Adventure|Fantasy|Sci-Fi" },
    { id: 712, title: "Burn After Reading", genres: "Comedy|Crime|Drama" },
    { id: 713, title: "Stars Look Down, The", genres: "Drama" },
    { id: 714, title: "Cremaster 2", genres: "Drama" },
    { id: 715, title: "Palestine Is Still the Issue", genres: "Documentary" },
    { id: 716, title: "Notti bianche, Le (White Nights)", genres: "Drama|Romance" },
    { id: 717, title: "Across the Pacific", genres: "Action|Adventure|Romance|War" },
    { id: 718, title: "Bleak Moments", genres: "Comedy|Drama" },
    { id: 719, title: "McCabe & Mrs. Miller", genres: "Drama|Western" },
    { id: 720, title: "Scarlet Letter, The (Der scharlachrote Buchstabe)", genres: "Drama" },
    { id: 721, title: "Underworld: Rise of the Lycans", genres: "Action|Fantasy|Horror|Thriller" },
    { id: 722, title: "Class of 1999", genres: "Action|Horror|Sci-Fi" },
    { id: 723, title: "Alice in Murderland", genres: "Horror|Thriller" },
    { id: 724, title: "History Is Made at Night", genres: "Drama|Romance" },
    { id: 725, title: "Jacob the Liar (Jakob, der Lügner)", genres: "Drama" },
    { id: 726, title: "School For Scoundrels", genres: "Comedy" },
    { id: 727, title: "Trailer Park Boys", genres: "Comedy|Crime" },
    { id: 728, title: "Vares: The Path of the Righteous Men (Vares - Kaidan tien kulkijat)", genres: "Crime|Drama" },
    { id: 729, title: "Hoot", genres: "Children|Comedy" },
    { id: 730, title: "Joy Ride", genres: "Adventure|Thriller" },
    { id: 731, title: "Jiminy Glick in La La Wood", genres: "Comedy|Mystery" },
    { id: 732, title: "Three Men and a Baby", genres: "Comedy" },
    { id: 733, title: "Broken Hearts Club, The", genres: "Drama" },
    { id: 734, title: "Shawshank Redemption, The", genres: "Crime|Drama" },
    { id: 735, title: "Making 'The New World'", genres: "Documentary" },
    { id: 736, title: "Winterhawk", genres: "Western" },
    { id: 737, title: "The Anomaly", genres: "Action|Sci-Fi|Thriller" },
    { id: 738, title: "Kill the Messenger", genres: "Crime|Drama|Mystery|Thriller" },
    { id: 739, title: "Heart of a Lion (Leijonasydän)", genres: "Drama|Romance" },
    { id: 740, title: "Brooklyn", genres: "Comedy|Drama|Romance" },
    { id: 741, title: "White Darkness, The", genres: "Documentary" },
    { id: 742, title: "Bat, The", genres: "Horror" },
    { id: 743, title: "Getting Go, the Go Doc Project", genres: "Drama" },
    { id: 744, title: "Flowers of St. Francis (Francesco, giullare di Dio)", genres: "Drama" },
    { id: 745, title: "Year of the Wolf, The (Suden vuosi)", genres: "Drama|Romance" },
    { id: 746, title: "My Sassy Girl", genres: "Comedy|Drama|Romance" },
    { id: 747, title: "Unrated II: Scary as Hell", genres: "Horror" },
    { id: 748, title: "Kingdom, The (Riget)", genres: "Drama|Horror|Mystery" },
    { id: 749, title: "Just a Kiss", genres: "Comedy|Romance" },
    { id: 750, title: "Very British Gangster, A", genres: "Crime|Documentary" },
    { id: 751, title: "Apart from You (After Our Separation) (Kimi to wakarete)", genres: "Drama" },
    { id: 752, title: "Ethel", genres: "Documentary" },
    { id: 753, title: "Strangeland", genres: "Thriller" },
    { id: 754, title: "Little Sister", genres: "Comedy" },
    { id: 755, title: "Scorched", genres: "Comedy|Crime" },
    { id: 756, title: "Kid & I, The", genres: "Comedy" },
    { id: 757, title: "Side Effects", genres: "Crime|Drama|Mystery|Thriller" },
    { id: 758, title: "Invincible", genres: "Drama" },
    { id: 759, title: "Falcon Rising", genres: "Action|Adventure" },
    { id: 760, title: "Extraterrestrial (Extraterrestre)", genres: "Comedy|Drama|Sci-Fi" },
    { id: 761, title: "Sound of Music, The", genres: "Musical|Romance" },
    { id: 762, title: "Merry-Go-Round", genres: "Drama" },
    { id: 763, title: "Hocus Pocus", genres: "Children|Comedy|Fantasy|Horror" },
    { id: 764, title: "Bring It On: Fight to the Finish", genres: "Comedy" },
    { id: 765, title: "Sun Shines Bright, The", genres: "Comedy|Drama" },
    { id: 766, title: "No One Writes to the Colonel (El coronel no tiene quien le escriba)", genres: "Drama" },
    { id: 767, title: "Mickey's The Prince and the Pauper", genres: "Animation|Children" },
    { id: 768, title: "Utamaro and His Five Women (Utamaro o meguru gonin no onna)", genres: "Drama" },
    { id: 769, title: "Apollo 13", genres: "Adventure|Drama|IMAX" },
    { id: 770, title: "14 Hours (Fourteen Hours)", genres: "Drama|Film-Noir|Thriller" },
    { id: 771, title: "Kamchatka", genres: "Drama" },
    { id: 772, title: "Fûke, De", genres: "Drama|War" },
    { id: 773, title: "Escape from the Planet of the Apes", genres: "Action|Sci-Fi" },
    { id: 774, title: "Cleo from 5 to 7 (Cléo de 5 à 7)", genres: "Drama" },
    { id: 775, title: "Weight of the Nation", genres: "Documentary" },
    { id: 776, title: "Serial", genres: "Comedy" },
    { id: 777, title: "Aziz Ansari: Buried Alive", genres: "Comedy" },
    { id: 778, title: "Kagerô-za", genres: "Fantasy|Romance|Thriller" },
    { id: 779, title: "Werewolf Boy, A (Neuk-dae-so-nyeon)", genres: "Drama|Fantasy|Romance" },
    { id: 780, title: "Plastic", genres: "Action|Crime" },
    { id: 781, title: "Song Remains the Same, The", genres: "Documentary|Musical" },
    { id: 782, title: "Voyage to the Bottom of the Sea", genres: "Adventure|Sci-Fi" },
    { id: 783, title: "Buckskin Frontier", genres: "Action|Western" },
    { id: 784, title: "2081", genres: "Action|Sci-Fi" },
    { id: 785, title: "Truth About Emanuel, The", genres: "Drama|Thriller" },
    { id: 786, title: "Naked Gun 2 1/2: The Smell of Fear, The", genres: "Comedy" },
    { id: 787, title: "I Am You (In Her Skin)", genres: "Drama|Thriller" },
    { id: 788, title: "Faith School Menace?", genres: "Documentary" },
    { id: 789, title: "21-87", genres: "Documentary" },
    { id: 790, title: "Essex Boys", genres: "Crime|Thriller" },
    { id: 791, title: "9 Star Hotel (Malon 9 Kochavim)", genres: "Documentary" },
    { id: 792, title: "Hawk Is Dying, The", genres: "Drama" },
    { id: 793, title: "Pretty Good for a Human (People Not as Bad as They Seem) (Aika hyvä ihmiseksi)", genres: "Comedy|Drama" },
    { id: 794, title: "NeverEnding Story III, The", genres: "Adventure|Children|Fantasy" },
    { id: 795, title: "I Am Not a Hipster", genres: "Drama" },
    { id: 796, title: "Stars Fell on Henrietta, The", genres: "Drama" },
    { id: 797, title: "Joe", genres: "Drama" },
    { id: 798, title: "Deterrence", genres: "Drama|Thriller" },
    { id: 799, title: "Innerspace", genres: "Action|Adventure|Comedy|Sci-Fi" },
    { id: 800, title: "Silent Action", genres: "Action|Crime|Drama" },
    { id: 801, title: "Dry Cleaning (Nettoyage à sec)", genres: "Drama" },
    { id: 802, title: "Fire in the Blood", genres: "Documentary" },
    { id: 803, title: "Doctor Zhivago", genres: "Drama|Romance|War" },
    { id: 804, title: "Frances", genres: "Drama" },
    { id: 805, title: "Prince & Me II: The Royal Wedding, The", genres: "Comedy|Romance" },
    { id: 806, title: "Game Change", genres: "Drama" },
    { id: 807, title: "Behind the Sun (Abril Despedaçado)", genres: "Drama" },
    { id: 808, title: "Passion of Joan of Arc, The (Passion de Jeanne d'Arc, La)", genres: "Drama" },
    { id: 809, title: "Undisputed III: Redemption", genres: "Action|Crime|Drama" },
    { id: 810, title: "Kansas", genres: "Crime|Drama" },
    { id: 811, title: "Transsiberian", genres: "Crime|Drama|Thriller" },
    { id: 812, title: "San Quentin", genres: "Drama" },
    { id: 813, title: "Broadcast News", genres: "Comedy|Drama|Romance" },
    { id: 814, title: "Wind That Shakes the Barley, The", genres: "Drama|War" },
    { id: 815, title: "Serial Killer Culture", genres: "Crime|Documentary" },
    { id: 816, title: "Order and Disorder", genres: "Documentary" },
    { id: 817, title: "Modify ", genres: "Documentary" },
    { id: 818, title: "Love at First Fight", genres: "Comedy|Romance" },
    { id: 819, title: "Ants in the Pants", genres: "Comedy|Romance" },
    { id: 820, title: "Won't Anybody Listen?", genres: "Documentary" },
    { id: 821, title: "Collision: Christopher Hitchens vs. Douglas Wilson", genres: "Documentary" },
    { id: 822, title: "Red Balloon, The (Ballon rouge, Le)", genres: "Children|Fantasy" },
    { id: 823, title: "Slums of Beverly Hills, The", genres: "Comedy|Drama" },
    { id: 824, title: "Control (Kontroll)", genres: "Comedy|Crime|Drama|Mystery" },
    { id: 825, title: "Coward, The (Kapurush)", genres: "Drama" },
    { id: 826, title: "Ed", genres: "Comedy" },
    { id: 827, title: "Mr. 3000", genres: "Comedy|Drama" },
    { id: 828, title: "Emergency Squad", genres: "Action|Thriller" },
    { id: 829, title: "MC5*: A True Testimonial", genres: "Documentary" },
    { id: 830, title: "My Neighbors the Yamadas (Hôhokekyo tonari no Yamada-kun)", genres: "Animation|Comedy" },
    { id: 831, title: "The Wind in the Willows", genres: "Adventure|Animation|Children|Comedy" },
    { id: 832, title: "Charlie Chan in Panama", genres: "Adventure|Comedy|Crime|Drama|Mystery|Thriller" },
    { id: 833, title: "Trek Nation", genres: "Documentary" },
    { id: 834, title: "Children Who Chase Lost Voices from Deep Below (Hoshi o ou kodomo) (Journey to Agartha)", genres: "Animation|Drama|Fantasy" },
    { id: 835, title: "Dinotopia: Quest for the Ruby Sunstone", genres: "Children|Fantasy|Sci-Fi" },
    { id: 836, title: "Godard's Passion (Passion)", genres: "Drama" },
    { id: 837, title: "Carny", genres: "Drama" },
    { id: 838, title: "Cats Don't Dance", genres: "Animation|Children|Musical" },
    { id: 839, title: "Unknown", genres: "Drama|Mystery|Thriller" },
    { id: 840, title: "Perfect Storm, The", genres: "Drama|Thriller" },
    { id: 841, title: "24 7: Twenty Four Seven", genres: "Comedy|Drama" },
    { id: 842, title: "Leprechaun: Origins", genres: "Horror" },
    { id: 843, title: "Patton", genres: "Drama|War" },
    { id: 844, title: "House", genres: "Comedy|Fantasy|Horror" },
    { id: 845, title: "Piano, The", genres: "Drama|Romance" },
    { id: 846, title: "Il Capitano", genres: "Drama" },
    { id: 847, title: "Coffy", genres: "Action|Crime|Thriller" },
    { id: 848, title: "End of St. Petersburg, The (Konets Sankt-Peterburga)", genres: "Drama" },
    { id: 849, title: "Blood on Satan's Claw (a.k.a. Satan's Skin)", genres: "Horror|Thriller" },
    { id: 850, title: "First Name: Carmen (Prénom Carmen)", genres: "Crime|Drama|Romance" },
    { id: 851, title: "Quiet City", genres: "Drama" },
    { id: 852, title: "Goodnight, Mister Tom", genres: "Drama" },
    { id: 853, title: "Fond Kiss, A (Ae Fond Kiss...)", genres: "Drama|Romance" },
    { id: 854, title: "From the Sky Down", genres: "Documentary" },
    { id: 855, title: "Vision (Vision - Aus dem Leben der Hildegard von Bingen)", genres: "Drama" },
    { id: 856, title: "American Flyers", genres: "Drama" },
    { id: 857, title: "Looking for Mr. Goodbar", genres: "Drama" },
    { id: 858, title: "Cutlet for Three (Ein Schnitzel für drei)", genres: "Comedy" },
    { id: 859, title: "Babe", genres: "Children|Drama" },
    { id: 860, title: "Urban Legend", genres: "Horror|Thriller" },
    { id: 861, title: "Who Am I? (Wo shi shei)", genres: "Action|Adventure|Comedy|Sci-Fi|Thriller" },
    { id: 862, title: "Cut", genres: "Comedy|Horror|Mystery|Thriller" },
    { id: 863, title: "Seven Invisible Men (Septyni nematomi zmones)", genres: "Drama" },
    { id: 864, title: "Weekend It Lives, The (Ax 'Em)", genres: "Horror" },
    { id: 865, title: "Wes Craven's New Nightmare (Nightmare on Elm Street Part 7: Freddy's Finale, A)", genres: "Drama|Horror|Mystery|Thriller" },
    { id: 866, title: "Keane", genres: "Mystery|Thriller" },
    { id: 867, title: "Mystery, Alaska", genres: "Children|Comedy" },
    { id: 868, title: "Man from Planet X, The", genres: "Horror|Romance|Sci-Fi" },
    { id: 869, title: "My Father's Glory (La gloire de mon père)", genres: "Adventure|Drama" },
    { id: 870, title: "Rain Over Santiago (Il pleut sur Santiago)", genres: "Documentary|Drama|War" },
    { id: 871, title: "Islander", genres: "Drama" },
    { id: 872, title: "Bookies", genres: "Comedy|Crime|Drama|Thriller" },
    { id: 873, title: "Compulsion", genres: "Drama|Thriller" },
    { id: 874, title: "Cold Sweat (De la part des copains)", genres: "Action|Drama|Thriller" },
    { id: 875, title: "Proposal, The", genres: "Comedy|Romance" },
    { id: 876, title: "Love Trap, The", genres: "Comedy|Romance" },
    { id: 877, title: "Black Room, The", genres: "Crime|Horror|Thriller" },
    { id: 878, title: "Running Scared", genres: "Action|Drama" },
    { id: 879, title: "Phantom, The", genres: "Action|Adventure" },
    { id: 880, title: "Lizzie McGuire Movie, The", genres: "Children|Comedy|Romance" },
    { id: 881, title: "Ski Party", genres: "Comedy" },
    { id: 882, title: "Mushrooming (Seenelkäik)", genres: "Adventure|Comedy|Thriller" },
    { id: 883, title: "Crossfire", genres: "Crime|Film-Noir" },
    { id: 884, title: "40 Days and 40 Nights", genres: "Comedy|Romance" },
    { id: 885, title: "Witches of Eastwick, The", genres: "Comedy|Fantasy|Horror|Thriller" },
    { id: 886, title: "Fatal Hour, The", genres: "Crime|Mystery|Thriller" },
    { id: 887, title: "Street Scene", genres: "Drama" },
    { id: 888, title: "Cranes Are Flying, The (Letyat zhuravli)", genres: "Drama|Romance|War" },
    { id: 889, title: "Hamlet (Gamlet)", genres: "Drama" },
    { id: 890, title: "Karate Kid, Part II, The", genres: "Action|Adventure|Drama" },
    { id: 891, title: "Born Reckless", genres: "Action|Adventure|Crime|Drama|Romance" },
    { id: 892, title: "Chinese Odyssey 2002 (Tian xia wu shuang)", genres: "Action|Comedy|Romance" },
    { id: 893, title: "Zelary", genres: "Drama|Romance" },
    { id: 894, title: "Poseidon Adventure, The ", genres: "Action|Adventure|Drama" },
    { id: 895, title: "Miracles", genres: "Comedy" },
    { id: 896, title: "Shall We Kiss? (Un baiser s'il vous plait)", genres: "Comedy|Romance" },
    { id: 897, title: "Ugly Truth, The", genres: "Comedy|Drama|Romance" },
    { id: 898, title: "Diaries of Vaslav Nijinsky, The", genres: "Documentary|Drama" },
    { id: 899, title: "Cat from Outer Space, The", genres: "Children|Comedy|Sci-Fi" },
    { id: 900, title: "Moonrise Kingdom", genres: "Comedy|Drama|Romance" },
    { id: 901, title: "City Hall", genres: "Drama|Thriller" },
    { id: 902, title: "Kickboxer 4: The Aggressor", genres: "Action|Thriller" },
    { id: 903, title: "Long Way Round", genres: "Adventure|Documentary" },
    { id: 904, title: "Kawasaki's Rose ", genres: "Drama" },
    { id: 905, title: "Phat Beach", genres: "Comedy" },
    { id: 906, title: "Skinwalkers", genres: "Horror|Thriller" },
    { id: 907, title: "Lost in the Desert", genres: "Adventure|Drama|Thriller" },
    { id: 908, title: "Love Is Colder Than Death (Liebe ist kälter als der Tod)", genres: "Comedy|Crime|Romance" },
    { id: 909, title: "Someone's Watching Me!", genres: "Horror|Mystery|Thriller" },
    { id: 910, title: "Staying Together", genres: "Comedy|Drama" },
    { id: 911, title: "Wild China", genres: "Documentary" },
    { id: 912, title: "Private Benjamin", genres: "Comedy" },
    { id: 913, title: "Wadjda", genres: "Drama" },
    { id: 914, title: "Lucifer Rising", genres: "Fantasy" },
    { id: 915, title: "Edvard Munch", genres: "Drama" },
    { id: 916, title: "Shatter Dead", genres: "Horror" },
    { id: 917, title: "Beloved Berlin Wall (Liebe Mauer)", genres: "Comedy|Drama|Romance" },
    { id: 918, title: "Happy Christmas", genres: "Comedy|Drama" },
    { id: 919, title: "Mandingo", genres: "Action|Romance" },
    { id: 920, title: "Skeletons", genres: "Comedy|Fantasy" },
    { id: 921, title: "Fun Size", genres: "Comedy" },
    { id: 922, title: "Wild Animals (Yasaeng dongmul bohoguyeog)", genres: "Crime|Drama" },
    { id: 923, title: "Abbott and Costello Meet Captain Kidd", genres: "Adventure|Comedy|Musical" },
    { id: 924, title: "Man on a Mission: Richard Garriott's Road to the Stars", genres: "Documentary" },
    { id: 925, title: "Invisible Invaders", genres: "Horror|Sci-Fi" },
    { id: 926, title: "Vertical Features Remake", genres: "Documentary" },
    { id: 927, title: "Thirst", genres: "Drama" },
    { id: 928, title: "My Science Project", genres: "Adventure|Sci-Fi" },
    { id: 929, title: "Star Kid", genres: "Adventure|Children|Fantasy|Sci-Fi" },
    { id: 930, title: "Elvis on Tour", genres: "Documentary|Musical" },
    { id: 931, title: "Intolerance: Love's Struggle Throughout the Ages", genres: "Drama" },
    { id: 932, title: "In the Name of the Father", genres: "Drama" },
    { id: 933, title: "Bellflower", genres: "Action|Drama|Romance" },
    { id: 934, title: "Stealing Beauty", genres: "Drama" },
    { id: 935, title: "Grease", genres: "Comedy|Musical|Romance" },
    { id: 936, title: "Devil's Backbone, The (Espinazo del diablo, El)", genres: "Drama|Fantasy|Horror|Thriller|War" },
    { id: 937, title: "Silverado", genres: "Action|Western" },
    { id: 938, title: "One Mile Away", genres: "Documentary" },
    { id: 939, title: "Shanghai Dreams (Qing hong)", genres: "Drama" },
    { id: 940, title: "Shoah", genres: "Documentary|War" },
    { id: 941, title: "Cookers", genres: "Drama|Horror|Thriller" },
    { id: 942, title: "Highlander III: The Sorcerer (a.k.a. Highlander: The Final Dimension)", genres: "Action|Fantasy" },
    { id: 943, title: "ATL", genres: "Drama" },
    { id: 944, title: "Reap the Wild Wind", genres: "Action|Adventure|Drama" },
    { id: 945, title: "Dante's Inferno", genres: "Action|Drama" },
    { id: 946, title: "Young and the Damned, The (Olvidados, Los)", genres: "Crime|Drama" },
    { id: 947, title: "Forbidden Christ, The (Cristo proibito, Il)", genres: "Drama" },
    { id: 948, title: "Librarian: Quest for the Spear, The", genres: "Action|Adventure|Comedy|Fantasy|Romance" },
    { id: 949, title: "Persuasion", genres: "Drama|Romance" },
    { id: 950, title: "Beyond the Law (Beyond the Law - Blue)", genres: "Comedy|Crime|Drama" },
    { id: 951, title: "Hole in the Head, A", genres: "Comedy|Musical" },
    { id: 952, title: "Mall", genres: "Drama" },
    { id: 953, title: "Slumming", genres: "Comedy|Drama" },
    { id: 954, title: "And Your Mother Too (Y tu mamá también)", genres: "Drama|Romance" },
    { id: 955, title: "Sherman's March", genres: "Documentary" },
    { id: 956, title: "Dr. Giggles", genres: "Comedy|Horror" },
    { id: 957, title: "Golem", genres: "Drama|Mystery|Sci-Fi" },
    { id: 958, title: "Project A ('A' gai waak)", genres: "Action|Comedy" },
    { id: 959, title: "Dangerous Woman, A", genres: "Drama|Romance" },
    { id: 960, title: "White: The Melody of the Curse", genres: "Horror" },
    { id: 961, title: "Almanya - Welcome to Germany (Almanya - Willkommen in Deutschland)", genres: "Comedy|Drama" },
    { id: 962, title: "Ethel", genres: "Documentary" },
    { id: 963, title: "Hiroshima ", genres: "Documentary" },
    { id: 964, title: "Walk in the Sun, A", genres: "War" },
    { id: 965, title: "Queen Christina", genres: "Drama|Romance" },
    { id: 966, title: "WolfCop", genres: "Comedy|Horror" },
    { id: 967, title: "North Star (a.k.a. Tashunga)", genres: "Action|Adventure|Crime|Drama|Western" },
    { id: 968, title: "People vs. Larry Flynt, The", genres: "Comedy|Drama" },
    { id: 969, title: "Kicking & Screaming", genres: "Comedy" },
    { id: 970, title: "Papadopoulos & Sons", genres: "Comedy|Drama" },
    { id: 971, title: "Dylan Moran Live: What It Is", genres: "Comedy" },
    { id: 972, title: "Switching Channels", genres: "Comedy" },
    { id: 973, title: "Ira and Abby", genres: "Comedy" },
    { id: 974, title: "House of Sand and Fog", genres: "Drama" },
    { id: 975, title: "Madam Satan", genres: "Comedy|Musical|Romance" },
    { id: 976, title: "Titus", genres: "Drama" },
    { id: 977, title: "Two Kilers (Kilerów 2-óch)", genres: "Comedy|Crime" },
    { id: 978, title: "Nömadak TX", genres: "Documentary|Musical" },
    { id: 979, title: "Downfall (Untergang, Der)", genres: "Drama|War" },
    { id: 980, title: "Double Life, A", genres: "Crime|Drama|Film-Noir" },
    { id: 981, title: "Double Trouble", genres: "Action|Comedy|Crime|Romance" },
    { id: 982, title: "Drinking Buddies", genres: "Comedy|Drama|Romance" },
    { id: 983, title: "American Crude", genres: "Comedy|Drama" },
    { id: 984, title: "Life with Mikey", genres: "Comedy" },
    { id: 985, title: "Xala", genres: "Comedy" },
    { id: 986, title: "Over-Eater, The (L'outremangeur)", genres: "Crime|Drama" },
    { id: 987, title: "Scooby-Doo! WrestleMania Mystery", genres: "Animation|Children" },
    { id: 988, title: "Higher Learning", genres: "Drama" },
    { id: 989, title: "Smokey and the Bandit", genres: "Action|Comedy" },
    { id: 990, title: "Rocket Singh: Salesman of the Year", genres: "Comedy|Drama" },
    { id: 991, title: "Rough Riders", genres: "Drama" },
    { id: 992, title: "Carnosaur", genres: "Horror|Sci-Fi" },
    { id: 993, title: "The Sign of Four: Sherlock Holmes' Greatest Case", genres: "Mystery" },
    { id: 994, title: "Dead Calling, A", genres: "Horror" },
    { id: 995, title: "Arctic Blast", genres: "Sci-Fi|Thriller" },
    { id: 996, title: "The Boy Next Door", genres: "Thriller" },
    { id: 997, title: "Pride & Prejudice", genres: "Drama|Romance" },
    { id: 998, title: "Aristocats, The", genres: "Animation|Children" },
    { id: 999, title: "Moonlight Murder", genres: "Mystery" },
    { id: 1000, title: "Thanks for Sharing", genres: "Comedy|Drama" }
];